# Generated by Django 3.1 on 2022-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad_project', '0002_auto_20220821_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='field',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
