# Generated by Django 3.1 on 2022-10-30 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notepad_project', '0004_auto_20221030_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
